# Generated by Django 5.2.4 on 2025-07-29 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='otp',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
