# Generated by Django 5.2.4 on 2025-07-31 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_otp_options_customuser_is_profile_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
