# Generated by Django 5.2.4 on 2025-08-04 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_full_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otp',
            options={'ordering': ['-created_at'], 'verbose_name': 'OTP', 'verbose_name_plural': 'OTPs'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(default='user@example.com', help_text="User's unique email address", max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(default='Default User', help_text="User's full name", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Optional phone number', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='code',
            field=models.CharField(help_text='6-digit OTP code', max_length=6),
        ),
        migrations.AlterField(
            model_name='otp',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Time when the OTP was created'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='is_used',
            field=models.BooleanField(default=False, help_text='Flag indicating if the OTP has been used'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='user',
            field=models.ForeignKey(help_text='User to whom the OTP belongs', on_delete=django.db.models.deletion.CASCADE, related_name='otps', to=settings.AUTH_USER_MODEL),
        ),
    ]
