version: '3.8'

services:
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

  backend:
    # This path now correctly points to your Django folder
    build: ./blogging_platform 
    command: gunicorn blogging_platform.wsgi:application --bind 0.0.0.0:8000
    volumes:
      # This also points to your Django folder for live code updates
      - ./blogging_platform:/app 
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db

  frontend:
    build:
      # This path now correctly points to your React folder
      context: ./blog_frontend 
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  postgres_data: