# Generated by Django 4.2.9 on 2025-07-23 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='singer',
            field=models.CharField(default='Unknown', max_length=30),
            preserve_default=False,
        ),
    ]
